[package]
name = "lazy-pax"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
pax-core = { git = "https://github.com/Santiago-Garrote/pax.git", tag = "1.1.0", version = "1.1.0", default-features = false }
ratatui = "0.30.2"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
